MiPrimerMVC/Controllers/NavigationMenuController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BootstrapMvcSample.Controllers;
using MiPrimerMVC.Models;

namespace MiPrimerMVC.Controllers
{
    public class NavigationMenuController : BootstrapBaseController
    {
        [ChildActionOnly]
        public ActionResult Render()
        {
            var menu = new MenuModel();
            menu.ApplicationTitle = "Clasificados";

            menu.MenuItems = new List<MenuItemModel>();
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                if (HttpContext.User.IsInRole("admin"))
                {
                    menu.MenuItems.Add(
                        new MenuItemModel
                        {
                            IsDropdown = false,
                            ActionLinkModel = new ActionLinkModel
                            {
                                Action = "Index2",
                                Controller = "Manage",
                                DisplayName = "Admin"
                            }
                        });
                }
                menu.MenuItems.Add(
                    new MenuItemModel
                    {
                        IsDropdown = false,
                        ActionLinkModel = new ActionLinkModel
                        {
                            Action = "Logoff",
                            Controller = "Account",
                            DisplayName = "Sign Out"
                        }
                    });
                menu.MenuItems.Add(new MenuItemModel
                {
                    IsDropdown = false,
                    ActionLinkModel = new ActionLinkModel
                    {
                        Action = "Create",
                        Controller = "Clasificados",
                        DisplayName = "Crear Clasificado"
                    }
                });
            }
            else
            {
                menu.MenuItems.Add(
                    new MenuItemModel
                    {
                        IsDropdown = false,
                        ActionLinkModel = new ActionLinkModel
                        {
                            Action = "SignIn",
                            Controller = "Account",
                            DisplayName = "Sign In"
                        }
                    });
                menu.MenuItems.Add(new MenuItemModel
                {
                    IsDropdown = false,
                    ActionLinkModel = new ActionLinkModel
                    {
                        Action = "Register",
                        Controller = "Account",
                        DisplayName = "Register"
                    }
                });
            }


            return PartialView(menu);
        }
    }
}

MiPrimerMVC/Views/Shared/Create.cshtml
@using BootstrapSupport
@model Object
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    
        <h4>@Model.GetLabel() <small>Details</small></h4>
        foreach (var property in Model.VisibleProperties())
        {
            <div class="form-group">
                @Html.Label(property.Name.ToSeparatedWords(), new {@class=""})
                    @Html.Editor(property.Name,new { htmlAttributes = new { @class = "form-control" }, })

                    @Html.ValidationMessage(property.Name, null, new { @class = "help-block" })    
            </div>
        }
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-link " })
          </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("input").addClass("form-control")
    });
</script>

MiPrimerMVC/Views/Shared/Delete.cshtml
@using BootstrapSupport
@model Object
@using (Html.BeginForm())
{
    <fieldset>
        <legend>@Model.GetLabel() <small>Details</small></legend>
        <dl> <!-- consider class="dl-horizontal" for horizontal styling -->
            @foreach (var property in Model.VisibleProperties())
            {
                <dt>
                    @property.GetLabel().ToSeparatedWords()
                </dt>
                <dd>
                    @Html.Display(property.Name)
                </dd>
            }
        </dl>
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
        </div>
    </fieldset>
}

MiPrimerMVC/Views/Shared/Details.cshtml
@using BootstrapSupport
@model Object
<fieldset>
    <legend>@Model.GetLabel() <small>Details</small></legend>
    <dl> <!-- consider adding class="dl-horizontal" for horizontal styling -->
        @foreach(var property in Model.VisibleProperties())
        {
            <dt>
                @property.GetLabel().ToSeparatedWords()
            </dt>
            <dd>
                @Html.Display(property.Name)                
            </dd>
        }
    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", Model.GetIdValue()) |
    @Html.ActionLink("Back to List", "Index")
</p>

MiPrimerMVC/Views/Shared/Index.cshtml
@using BootstrapSupport
@model System.Collections.IEnumerable   
    <h4>@Model.GetLabel() <small>Listing</small></h4>
<table class="table table-striped">
    <caption></caption>
    <thead>
        <tr>
            @foreach (var property in Model.VisibleProperties())
            {
                <th>
                    @property.GetLabel().ToSeparatedWords()
                </th>
            }
            <th></th>
        </tr>
    </thead>
    @{ int index = 0; }
    @foreach (var model in Model)
    {
        ViewData[index.ToString()] = model;
        <tr>
            @foreach (var property in model.VisibleProperties())
            {
                <td>
                    @Html.Display(index + "." + property.Name)
                </td>                    
            }
            <td>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        Action <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        @{
                            @Html.TryPartial("_actions", model)                            
                            var routevalues = model.GetIdValue();  
                            <li>@Html.ActionLink("Edit", "Edit", routevalues)</li>
                            <li>@Html.ActionLink("Details", "Details", routevalues)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Delete", "Delete", routevalues)</li>
                               
                        }
                    </ul>
                </div>

            </td>
        </tr>
            index++;
    }

</table>
<p>
    @Html.ActionLink("Create New", "Create", null, new {@class = "btn btn-default"})
</p>

MiPrimerMVC/Views/Shared/_BootstrapLayout.basic.cshtml
@using System.Web.Optimization
@using BootstrapSupport
@using Microsoft.Web.Mvc.Controls
@using Microsoft.Web.Mvc.Html
@using NavigationRoutes
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="@Styles.Url("~/content/css")" rel="stylesheet"/>
        @RenderSection("head", required: false)
        @Html.Partial("_html5shiv")
        @* favicons and touch icons go here *@
    </head>
    <body>
        
        @Html.Action("Render","NavigationMenu")
        
        @*@Html.Partial("_navigationMenu")*@
        
        <div class="container">
            @Html.Partial("_alerts")
            @Html.Partial("_validationSummary")
            @RenderBody()   
            <hr>
            <footer>
                <p>&copy; Company @System.DateTime.Now.ToString("yyyy")</p>
            </footer> 
        </div>
        @Scripts.Render("~/js")
        @RenderSection("Scripts", required: false)
    </body>
</html>

MiPrimerMVC/Views/Shared/_BootstrapLayout.empty.cshtml
@using System.Web.Optimization
@using BootstrapSupport
@using NavigationRoutes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Styles.Url("~/content/css")" rel="stylesheet"/>
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }

            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }

            .form-signin .checkbox {
                font-weight: normal;
            }

            .form-signin .form-control {
                position: relative;
                height: auto;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
                padding: 10px;
                font-size: 16px;
            }

                .form-signin .form-control:focus {
                    z-index: 2;
                }

            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }

            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }


    </style>    <link href="@Styles.Url("~/Content/css-responsive")" rel="stylesheet" type="text/css" />
    @RenderSection("head", required: false)
    @Html.Partial("_html5shiv")
    @* favicons and touch icons go here *@
</head>
<body>
    <div class="container">

        @Html.Partial("_alerts")
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; Company @System.DateTime.Now.ToString("yyyy")</p>
        </footer>

    </div> <!-- container -->
    @Scripts.Render("~/js")
    @RenderSection("Scripts", required: false)
</body>
</html>

MiPrimerMVC/Views/Shared/_BootstrapLayout.narrow.cshtml
@using System.Web.Optimization
@using BootstrapSupport
@using NavigationRoutes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Styles.Url("~/content/css")" rel="stylesheet"/>
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }

      /* added to trim our long nav menu to a more appropriate appearance */
      .masthead .nav {
          max-width: 416px;
          height: 3em;
      }
    </style>
    <link href="@Styles.Url("~/Content/css-responsive")" rel="stylesheet" type="text/css" />
    @RenderSection("head", required: false)
    @Html.Partial("_html5shiv")
    @* favicons and touch icons go here *@
</head>
<body>
    <div class="container-narrow">

        <div class="masthead">
            <ul class="nav nav-pills pull-right">
                @Html.Navigation()
            </ul>
            <h3 class="muted">MvcApplication1</h3>
        </div>

        @Html.Partial("_alerts")
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; Company @System.DateTime.Now.ToString("yyyy")</p>
        </footer>

    </div> <!-- container -->
    @Scripts.Render("~/js")
    @RenderSection("Scripts", required: false)
</body>
</html>

MiPrimerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mis Clasificados", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top: 15px;">
        
        <div class="row">
            <div class="col-lg-3">
                
            </div>
            <div class="col-lg-9">
                @RenderBody()        
            </div>
        </div>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiPrimerMVC/Views/Shared/_LayoutBasic.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/content/sigin")
</head>
    <body>
        <div class="container">
            @RenderBody()
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

MiPrimerMVC/Views/Shared/_alerts.cshtml
@using BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attention!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach(string key in Alerts.ALL.Except(new[] {Alerts.ATTENTION}))
    {
        if (TempData.ContainsKey(key))
         {
             <div class="alert alert-@key" role="alert">
                 <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                 @TempData[key]
             </div>
         }
    }

MiPrimerMVC/Views/Shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->

MiPrimerMVC/Views/Shared/_navigationMenu.cshtml
@using NavigationRoutes
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @if (HttpContext.Current.User.Identity.IsAuthenticated == false)
                {
                    <li>
                        @Html.ActionLink("Sign In", "Login", "Account")    
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        @Html.ActionLink("Register", "Register", "Account")    
                    </li>
                }
                else
                {
                    <li>
                        <a href="admin/manage/index2">Administrar</a>    
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        @Html.ActionLink("Crear Clasificado", "Create", "Clasificados")    
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        @Html.ActionLink("Sign Out", "Logoff", "Account")    
                    </li>
                    
                }
                
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

MiPrimerMVC/Views/Shared/_validationSummary.cshtml
@{
    // NOTE: This constant controls whether property validation failures will be excluded from the summary
    const bool ExcludePropertyFailures = true;
    var renderSummary = false;

    if (ExcludePropertyFailures)
    {
        // Here we need to figure out if there are going to be any validation failures that are not related to a property
        // If there are none found, we don't want to display the alert div

        // This logic is taken from System.Web.Mvc.Html.ValidationExtensions.GetModelStateList(HtmlHelper htmlHelper, bool excludePropertyErrors)
        // which is eventually invoked by calling @Html.ValidationSummary(ExcludePropertyFailures)
        // The call to ViewData.ModelState.TryGetValue will determine whether there are any validation failures that are not related to a property
        ModelState state;
        ViewData.ModelState.TryGetValue(ViewData.TemplateInfo.HtmlFieldPrefix, out state);

        if (state != null)
        {
            renderSummary = true;
        }
    }
    else
    {
        if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
        {
            renderSummary = true;
        }
    }

    if (renderSummary)
    {
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">&times;</a>
            @Html.ValidationSummary(ExcludePropertyFailures)
        </div>
    }
}